### ISSUE TITLE
Keys are mapped in the reverse order.

### ISSUE THREAD

**Issue by simadude** [nvim-computercraft/lua-ls-cc-tweaked#6]
The way that keys are used in CC are string to integer value. The `library/keys.lua` file has them the other way around.
Just change from this:
```lua
keys = {
	[numkey] = "key"
	...
}
```
To this:
```lua
keys = {
	["key"] = numkey
	...
}
```

**Comment by bananasov** [comment]
Is this really necessary? CC: Tweaked automatically generates them [here](https://github.com/cc-tweaked/CC-Tweaked/blob/d77f5f135f9251d027cc900dc27fd80160b632b9/projects/core/src/main/resources/data/computercraft/lua/rom/apis/keys.lua#L137-L140)

**Comment by simadude** [comment]
Yeah, except the annotations now try to tell you that you can, for example, access a field `keys[257]` and expect to get a string `"return"`, which is not the case. Also there is no completion on the naming of the keys.

The correct way would be to not just swap the keys/values, but also remove the quotation marks so the annotations wouldn't try to switch `keys.right` to `keys["right"]` (they are the same thing, but the first one is objectively better.)
