### ISSUE TITLE
Cannot initiate websocket with table

### ISSUE THREAD

**Issue by piprett** [nvim-computercraft/lua-ls-cc-tweaked#7]
> Or
>  request { url = [string](https://www.lua.org/manual/5.1/manual.html#5.4), headers? = { [[string](https://www.lua.org/manual/5.1/manual.html#5.4)] = [string](https://www.lua.org/manual/5.1/manual.html#5.4) }, timeout? = number }

**Comment by bananasov** [comment]
~~where did you even see this, I don't see it in the http definitions~~

found it, send a link next time instead of quoting it to give more context
